ALTER TABLE clinic_days ADD COLUMN clinic TEXT NOT NULL DEFAULT 'harley';
ALTER TABLE clinic_days ADD COLUMN private_fees REAL NOT NULL DEFAULT 0;
ALTER TABLE clinic_days ADD COLUMN plan_checkups INTEGER NOT NULL DEFAULT 0;
ALTER TABLE clinic_days ADD COLUMN plan_hygiene INTEGER NOT NULL DEFAULT 0;
ALTER TABLE clinic_days ADD COLUMN lab_cost REAL NOT NULL DEFAULT 0;
ALTER TABLE clinic_days ADD COLUMN dd_amount REAL NOT NULL DEFAULT 0;
